# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
            python3 utils.py
          environment:
            database_username: root
            database_pwd: circleci
            database_host: localhost
            database_db: book_lending_club
      - run:
          name: run application
          command: |
            . venv/bin/activate
            python3 run.py
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-reports
            flake8 --exclude=venv* --statistics
            python3 test.py 
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
