# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run application
          command: |
            python3 run.py
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            mkdir test-reports
            flake8 --exclude=venv* --statistics
            python3 test.py 
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
